# Generated by Django 5.0.1 on 2024-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=50)),
                ('Actor_Character_Name', models.CharField(max_length=50)),
                ('Actress_Character_Name', models.CharField(max_length=50)),
                ('Actor_Name', models.CharField(max_length=50)),
                ('Actress_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
